try:
    from rivoli.secrets import (
        RIVOLI_BOT_SLACK,
        RIVOLI_TWITTER_ACCESS_TOKEN,
        RIVOLI_TWITTER_ACCESS_TOKEN_SECRET,
        RIVOLI_TWITTER_CUSTOMER_API_KEY,
        RIVOLI_TWITTER_CUSTOMER_API_SECRET_KEY,
        SEBASTOPOL_TWITTER_ACCESS_TOKEN,
        SEBASTOPOL_TWITTER_ACCESS_TOKEN_SECRET,
        SEBASTOPOL_TWITTER_CUSTOMER_API_KEY,
        SEBASTOPOL_TWITTER_CUSTOMER_API_SECRET_KEY,
        RIVOLI_URL,
        SEBASTOPOL_URL,
    )
except ImportError:
    import os

    RIVOLI_BOT_SLACK = os.environ['RIVOLI_BOT_SLACK']
    RIVOLI_TWITTER_ACCESS_TOKEN = os.environ['RIVOLI_TWITTER_ACCESS_TOKEN']
    RIVOLI_TWITTER_ACCESS_TOKEN_SECRET = os.environ['RIVOLI_TWITTER_ACCESS_TOKEN_SECRET']
    RIVOLI_TWITTER_CUSTOMER_API_KEY = os.environ['RIVOLI_TWITTER_CUSTOMER_API_KEY']
    RIVOLI_TWITTER_CUSTOMER_API_SECRET_KEY = os.environ['RIVOLI_TWITTER_CUSTOMER_API_SECRET_KEY']
    SEBASTOPOL_TWITTER_ACCESS_TOKEN = os.environ['SEBASTOPOL_TWITTER_ACCESS_TOKEN']
    SEBASTOPOL_TWITTER_ACCESS_TOKEN_SECRET = os.environ['SEBASTOPOL_TWITTER_ACCESS_TOKEN_SECRET']
    SEBASTOPOL_TWITTER_CUSTOMER_API_KEY = os.environ['SEBASTOPOL_TWITTER_CUSTOMER_API_KEY']
    SEBASTOPOL_TWITTER_CUSTOMER_API_SECRET_KEY = os.environ['SEBASTOPOL_TWITTER_CUSTOMER_API_SECRET_KEY']
    SEBASTOPOL_URL = os.environ['SEBASTOPOL_URL']
    RIVOLI_URL = os.environ['RIVOLI_URL']
